application: realistictaxidermy
version: live
runtime: python
api_version: 1

handlers:

- url: /galleryData
  script: picassaProxy.py

- url: /
  mime_type: text/html
  static_files: static/Home.html
  upload: static/Home.html

- url: /static
  static_dir: static

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /Gallery.html
  static_files: static/Gallery.html
  upload: static/Gallery.html
  
- url: /Contact.html
  static_files: static/Contact.html
  upload: static/Contact.html

- url: /Links.html
  static_files: static/Links.html
  upload: static/Links.html
